name: Test

on:
  push:
    branches:
    - v4

  pull_request:
    branches:
    - v4

permissions:
  contents: read

jobs:

  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_HOSTNAME: postgres
          POSTGRES_DB: mgrt
          POSTGRES_USER: mgrt
          POSTGRES_PASSWORD: secret

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v6
      with:
        go-version: '1.24'
    - run: go version

    - name: Run tests
      run: go test -v -coverprofile coverage ./...
      env:
        PG_ADDR: postgresql://mgrt:secret@postgres:5432/mgrt
